version: 2.1

executors:
  go-112:
    docker:
      - image: circleci/golang:1.12
    environment:
      - GOROOT: /usr/local/go
    working_directory: /home/circleci/go/src/github.com/ramenjuniti/jtfidf

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build:
    executor: go-112
    steps:
      - run:
          name: install
          command: |
            go get github.com/ramenjuniti/jtfidf
      - run:
          name: test
          command: |
            go test -v -cover -coverprofile=coverage.txt github.com/ramenjuniti/jtfidf
      - codecov/upload:
          file: /home/circleci/go/src/github.com/ramenjuniti/jtfidf/coverage.txt
