version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    environment:
      - GOROOT: /usr/local/go
    working_directory: /home/circleci/go/src/github.com/ramenjuniti/jtfidf
    orbs:
      codecov: codecov/codecov@1.0.4
    steps:
      - run:
          name: install
          command: |
            go get github.com/ramenjuniti/jtfidf
      - run:
          name: test
          command: |
            go test -v -cover -coverprofile=coverage.out github.com/ramenjuniti/jtfidf
      - codecov/upload:
          file: ./coverage.out
