version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    environment:
      - GOROOT: /usr/local/go
    working_directory: /home/circleci/go/src/github.com/ramenjuniti/jtfidf
    steps:
      - run:
          name: install
          command: |
            go get -u github.com/ramenjuniti/jtfidf
      - run:
          name: test
          command: |
            go test -v ./...
