version: 2.1

executors:
  go-112:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/ramenjuniti/jtfidf

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build:
    executor: go-112
    steps:
      - checkout
      - restore_cache:
          keys:
            - golint
            - kagome
      - run:
          name: Checking golint
          command: |
            if ! type golint >/dev/null 2>&1; then
              go get -u golang.org/x/lint/golint
            fi
            golint -set_exit_status ./...
      - save_cache:
          key: golint
          paths:
            - /go/bin/golint
      - run:
          name: install
          command: |
            go get -u github.com/ikawaha/kagome/...
      - save_cache:
          key: kagome
          paths:
            - /go/src/github.com/ikawaha/kagome
      - run:
          name: Testing
          command: |
            go test -v -race -cover -coverprofile=coverage.out ./...
      - codecov/upload:
          file: ./coverage.out
